name: image
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  image_cropper: ^4.0.1
  
  permission_handler: ^11.3.1
  screenshot: ^2.3.0
  image_gallery_saver: ^2.0.3
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  flutter_colorpicker: ^1.0.3
  draw_your_image: ^0.2.0
  painter: ^2.0.0
  # flutter_painter: ^1.0.1
  phosphor_flutter: ^2.0.1
  # stickereditor: ^0.0.8
  google_fonts: ^4.0.4
  extended_image: ^8.0.2
  stick_it: ^1.0.0+2
  uuid: ^4.3.3
  gallery_saver: ^2.3.2
  aligned_dialog: ^0.0.7
  # gallery_saver: ^2.3.2
  # flutter_simple_sticker_view: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true
  fonts:
  - family: PlayfairDisplay
    fonts:
      - asset: fonts\PlayfairDisplay-Bold.ttf
      - asset: fonts\PlayfairDisplay-Medium.ttf


  # To add assets to your application, add an assets section, like this:
  assets:
    
    - assets/images/l.png
    - assets/images/s.png
    - assets/images/o.png
    - assets/images/g.png
    - assets/images/r.png
    - assets/images/mm.png
    - assets/images/sd.png
    - assets/images/ff.png
    - assets/images/op2.png
  #   - images/a_dot_ham.jpeg
